account_type: common
realm: nonprod
env: common-nonprod

features:
  networking:
    enabled: true
    version: feature-networking-v0.2.1
    cidr: 10.101.0.0/16
    secondary_cidrs: [10.102.0.0/16]
    availability_zones: [eu-west-1a, eu-west-1b]

    flow_logs:
      enabled: false

  amg:
    enabled: true
    version: feature-amg-v0.1.0

  amp:
    enabled: true
    version: feature-amp-v0.1.1
