account_type: app
realm: nonprod
env: dev

features:
  networking:
    enabled: true
    #version: feature-networking-v0.5.0
    version: fix-tags-refactor
    cidr: 10.111.0.0/16
    secondary_cidrs: [10.102.9.0/24]
    availability_zones: [eu-west-1a, eu-west-1b]
    egress_subnets: [10.102.9.16/28, 10.102.9.32/28]
    platform_subnets: [10.111.1.0/24, 10.111.2.0/24]

    flow_logs:
      enabled: false

  ecs-plf:
    enabled: true
    #version: feature-ecs-plf-v0.2.0
    version: fix-tags-refactor
