name: OpenTofu CI

inputs:
  component-type:
    description: "Type of component to run CI on, eg: `feature`"
    required: true
  component-name:
    description: "Name of the component to run CI on, eg: `networking`"
    required: true

runs:
  using: composite
  shell: /bin/bash
  steps:
  - name: Install OpenTofu
    uses: opentofu/setup-opentofu@v1

  - name: Run CI job
    run: make ci-${{ inputs.component-type }}-${{ inputs.component-name }}
