name: OpenTofu CI

inputs:
  component-type:
    description: "Type of component to run CI on, eg: `feature`"
    required: true
  component-name:
    description: "Name of the component to run CI on, eg: `networking`"
    required: true

runs:
  using: composite
  steps:
  - name: Install OpenTofu
    uses: opentofu/setup-opentofu@v1

  - name: Ensure TF cache folder exists
    shell: bash
    run: mkdir -p /tmp/tf-cache

  - name: Restore or create the TF cache
    uses: actions/cache@v4
    with:
      path: /tmp/tf-cache
      key: ${{ runner.os }}-tf-${{ inputs.component-type }}-${{ inputs.component-name }}
      restore-keys: |
        ${{ runner.os }}-tf-${{ inputs.component-type }}
        ${{ runner.os }}-tf-

  - name: Run CI job
    shell: bash
    env:
      TF_PLUGIN_CACHE_DIR: /tmp/tf-cache
    run: |
      make ci-${{ inputs.component-type }}-${{ inputs.component-name }}
